server {
    listen 80;
    server_name tiadmintan13.titanvpn.kr;

    access_log /var/log/nginx/titan-admin_access.log;
    error_log /var/log/nginx/titan-admin_error.log;

    location / {
        include uwsgi_params;
        uwsgi_pass unix:/tmp/titan-admin.sock;
        uwsgi_read_timeout 60;
        uwsgi_buffers 8 16k;
        uwsgi_buffer_size 16k;
    }

    location /static/ {
        alias /home/newkorea/project/titan-admin/backend/static/;
        expires 30d;
        access_log off;
    }

    location /upload/ {
        alias /home/newkorea/project/titan/upload/;
        expires -1;
    }
}
