# Generated by Django 2.2.5 on 2025-06-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblPaymentApiLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(max_length=10, null=True)),
                ('payment_amount', models.IntegerField(null=True)),
                ('payment_time', models.CharField(max_length=10, null=True)),
                ('ip_address', models.CharField(max_length=45, null=True)),
                ('user_agent', models.TextField(null=True)),
                ('raw_payload', models.TextField(null=True)),
                ('result_message', models.TextField(null=True)),
                ('status', models.CharField(default='PENDING', max_length=10)),
            ],
        ),
    ]
