[uwsgi]
chdir = /home/newkorea/project/uto-admin
module = main.wsgi:application
home = /home/newkorea/project/uto-admin/.venv38

master = true
processes = 2
enable-threads = true

socket = /tmp/uto-admin.sock
chmod-socket = 666
pidfile = /tmp/uto-admin.pid
vacuum = true
die-on-term = true
harakiri = 120
harakiri-verbose = true

touch-reload = /home/newkorea/project/uto-admin/main/reload

logto = /home/newkorea/project/uto-admin/logs/uwsgi.log
