[uwsgi]
vhost = true
# Tighter permissions; nginx should share group or run via proxy
chmod-socket = 666
socket = /tmp/titan-admin.sock
master = true
enable-threads = true
processes = 2
venv = /home/newkorea/project/titan-admin/.venv38
wsgi-file = /home/newkorea/project/titan-admin/main/wsgi.py
chdir = /home/newkorea/project/titan-admin
touch-reload = /home/newkorea/project/titan-admin/main/reload
pidfile = /tmp/titan-admin.pid
vacuum = true
die-on-term = true
harakiri = 120
harakiri-verbose = true
daemonize = /home/newkorea/project/titan-admin/logs/uwsgi.log
module = main.wsgi:application
