[uwsgi]
vhost = true
chmod-socket = 666
socket = /tmp/uto-admin.sock
master = true
enable-threads = true
processes = 2
venv = /home/newkorea/project/uto-admin/.venv38
wsgi-file = /home/newkorea/project/uto-admin/main/wsgi.py
chdir = /home/newkorea/project/uto-admin
touch-reload = /home/newkorea/project/uto-admin/main/reload
pidfile = /tmp/uto-admin.pid
vacuum = true
die-on-term = true
harakiri = 120
harakiri-verbose = true
daemonize = /home/newkorea/project/uto-admin/logs/uwsgi.log
module = main.wsgi:application
