# Generated by Django 2.2.5 on 2025-02-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nasname', models.CharField(max_length=128)),
                ('shortname', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('ports', models.IntegerField(blank=True, null=True)),
                ('secret', models.CharField(max_length=60)),
                ('server', models.CharField(blank=True, max_length=64, null=True)),
                ('community', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'nas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radacct',
            fields=[
                ('radacctid', models.BigAutoField(primary_key=True, serialize=False)),
                ('acctsessionid', models.CharField(max_length=64)),
                ('acctuniqueid', models.CharField(max_length=32, unique=True)),
                ('username', models.CharField(max_length=64)),
                ('groupname', models.CharField(max_length=64)),
                ('realm', models.CharField(blank=True, max_length=64, null=True)),
                ('nasipaddress', models.CharField(max_length=15)),
                ('nasportid', models.CharField(blank=True, max_length=15, null=True)),
                ('nasporttype', models.CharField(blank=True, max_length=32, null=True)),
                ('acctstarttime', models.DateTimeField(blank=True, null=True)),
                ('acctstoptime', models.DateTimeField(blank=True, null=True)),
                ('acctsessiontime', models.PositiveIntegerField(blank=True, null=True)),
                ('acctauthentic', models.CharField(blank=True, max_length=32, null=True)),
                ('connectinfo_start', models.CharField(blank=True, max_length=50, null=True)),
                ('connectinfo_stop', models.CharField(blank=True, max_length=50, null=True)),
                ('acctinputoctets', models.BigIntegerField(blank=True, null=True)),
                ('acctoutputoctets', models.BigIntegerField(blank=True, null=True)),
                ('calledstationid', models.CharField(max_length=50)),
                ('callingstationid', models.CharField(max_length=50)),
                ('acctterminatecause', models.CharField(max_length=32)),
                ('servicetype', models.CharField(blank=True, max_length=32, null=True)),
                ('framedprotocol', models.CharField(blank=True, max_length=32, null=True)),
                ('framedipaddress', models.CharField(max_length=15)),
                ('acctstartdelay', models.PositiveIntegerField(blank=True, null=True)),
                ('acctstopdelay', models.PositiveIntegerField(blank=True, null=True)),
                ('xascendsessionsvrkey', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'radacct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radcheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'db_table': 'radcheck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radgroupcheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'db_table': 'radgroupcheck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radgroupreply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'db_table': 'radgroupreply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radpostauth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('pass_field', models.CharField(db_column='pass', max_length=64)),
                ('reply', models.CharField(max_length=32)),
                ('authdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'radpostauth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radreply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'db_table': 'radreply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radusergroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('groupname', models.CharField(max_length=64)),
                ('priority', models.IntegerField()),
            ],
            options={
                'db_table': 'radusergroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SampleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sample_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hostdomain', models.CharField(max_length=200)),
                ('hostip', models.CharField(max_length=100)),
                ('is_active', models.IntegerField()),
                ('is_status', models.IntegerField()),
                ('pd_name', models.CharField(blank=True, max_length=15, null=True)),
                ('telecom', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'tbl_agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAgentFailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('app_version', models.CharField(blank=True, max_length=255, null=True)),
                ('server_name', models.CharField(blank=True, max_length=255, null=True)),
                ('server_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('server_protocol', models.CharField(blank=True, max_length=255, null=True)),
                ('user_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('user_location', models.CharField(blank=True, max_length=200, null=True)),
                ('device_info', models.CharField(blank=True, max_length=200, null=True)),
                ('failed_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_agent_failed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllowIp',
            fields=[
                ('ip', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_allow_ip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAndroidVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ver_code', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'tbl_android_version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblBankAccount',
            fields=[
                ('type', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_number', models.CharField(max_length=255)),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_bank_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblChinaApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
                ('package_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_china_app',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCodeDetail',
            fields=[
                ('group_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('memo', models.CharField(blank=True, max_length=10000, null=True)),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('delete_yn', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'tbl_code_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCodeGroup',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('memo', models.CharField(blank=True, max_length=10000, null=True)),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('delete_yn', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'tbl_code_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCompanyManage',
            fields=[
                ('type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('en', models.TextField(blank=True, null=True)),
                ('ko', models.TextField(blank=True, null=True)),
                ('ja', models.TextField(blank=True, null=True)),
                ('zh', models.TextField(blank=True, null=True)),
                ('en_modify_date', models.DateTimeField(blank=True, null=True)),
                ('ko_modify_date', models.DateTimeField(blank=True, null=True)),
                ('ja_modify_date', models.DateTimeField(blank=True, null=True)),
                ('zh_modify_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_company_manage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDownloadManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('client_name', models.CharField(blank=True, max_length=300, null=True)),
                ('image_name', models.CharField(blank=True, max_length=300, null=True)),
                ('client_real_size', models.IntegerField(blank=True, null=True)),
                ('client_save_size', models.CharField(blank=True, max_length=300, null=True)),
                ('client_save_path', models.CharField(blank=True, max_length=300, null=True)),
                ('client_modify_date', models.DateTimeField(blank=True, null=True)),
                ('image_real_size', models.IntegerField(blank=True, null=True)),
                ('image_save_size', models.CharField(blank=True, max_length=300, null=True)),
                ('image_save_path', models.CharField(blank=True, max_length=300, null=True)),
                ('image_modify_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_download_manage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblEventCode',
            fields=[
                ('event_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('free_day', models.IntegerField()),
                ('reward_percent', models.IntegerField()),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('delete_yn', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'tbl_event_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblFakeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fake_code', models.CharField(max_length=255)),
                ('fake_cnt', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_fake_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(blank=True, max_length=255, null=True)),
                ('gid', models.CharField(blank=True, max_length=255, null=True)),
                ('real_name', models.CharField(max_length=255)),
                ('save_name', models.CharField(max_length=255)),
                ('ext', models.CharField(max_length=255)),
                ('real_size', models.IntegerField()),
                ('save_size', models.CharField(max_length=255)),
                ('save_path', models.CharField(max_length=255)),
                ('regist_id', models.CharField(blank=True, max_length=255, null=True)),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('delete_yn', models.CharField(blank=True, max_length=10, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMenuManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('use_yn', models.CharField(max_length=10)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_menu_manage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_en', models.TextField(blank=True, null=True)),
                ('content_ko', models.TextField(blank=True, null=True)),
                ('content_zh', models.TextField(blank=True, null=True)),
                ('platform', models.TextField(blank=True, null=True)),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('delete_yn', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'tbl_notice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNoticeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_notice_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblOsxVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver_code', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_osx_version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('alipay', 'Alipay'), ('wechat', 'WeChat')], max_length=10)),
                ('payment_time', models.TimeField()),
                ('payment_amount', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('API_date', models.DateTimeField(auto_now_add=True)),
                ('regist_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_send_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPolicyManage',
            fields=[
                ('type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('en', models.TextField(blank=True, null=True)),
                ('ko', models.TextField(blank=True, null=True)),
                ('ja', models.TextField(blank=True, null=True)),
                ('zh', models.TextField(blank=True, null=True)),
                ('en_modify_date', models.DateTimeField(blank=True, null=True)),
                ('ko_modify_date', models.DateTimeField(blank=True, null=True)),
                ('ja_modify_date', models.DateTimeField(blank=True, null=True)),
                ('zh_modify_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_policy_manage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_session', models.CharField(blank=True, max_length=100, null=True)),
                ('type_month', models.CharField(blank=True, max_length=100, null=True)),
                ('item_price', models.CharField(blank=True, max_length=100, null=True)),
                ('item_price_usd', models.CharField(blank=True, max_length=100, null=True)),
                ('item_price_jpy', models.CharField(blank=True, max_length=100, null=True)),
                ('item_price_cny', models.CharField(blank=True, max_length=100, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('modify_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.IntegerField()),
                ('pgcode', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('session', models.IntegerField(blank=True, null=True)),
                ('month_type', models.IntegerField(blank=True, null=True)),
                ('krw', models.CharField(blank=True, max_length=100, null=True)),
                ('usd', models.CharField(blank=True, max_length=100, null=True)),
                ('jpy', models.CharField(blank=True, max_length=100, null=True)),
                ('cny', models.CharField(blank=True, max_length=100, null=True)),
                ('taxfree_amount', models.IntegerField(blank=True, null=True)),
                ('tax_amount', models.IntegerField(blank=True, null=True)),
                ('autopay_flag', models.CharField(blank=True, max_length=10, null=True)),
                ('billkey', models.CharField(blank=True, max_length=255, null=True)),
                ('refund_yn', models.CharField(blank=True, max_length=10, null=True)),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('refund_date', models.DateTimeField(blank=True, null=True)),
                ('auto_end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_price_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblRegistBan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=255, unique=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('delete_yn', models.CharField(blank=True, max_length=10, null=True)),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_regist_ban',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('star', models.IntegerField()),
                ('content', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=200)),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('regist_id', models.IntegerField(blank=True, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('modify_id', models.IntegerField(blank=True, null=True)),
                ('delete_yn', models.CharField(blank=True, max_length=10, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblRewardLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewarder_id', models.IntegerField()),
                ('registrant_id', models.IntegerField()),
                ('reward_days', models.IntegerField()),
                ('type', models.IntegerField()),
                ('register_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_reward_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblRewardSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('register_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_reward_setting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSendHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('session', models.IntegerField(blank=True, null=True)),
                ('month_type', models.IntegerField(blank=True, null=True)),
                ('krw', models.CharField(blank=True, max_length=100, null=True)),
                ('usd', models.CharField(blank=True, max_length=100, null=True)),
                ('jpy', models.CharField(blank=True, max_length=100, null=True)),
                ('cny', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('accept_date', models.DateTimeField(blank=True, null=True)),
                ('cancel_date', models.DateTimeField(blank=True, null=True)),
                ('refund_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_send_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblServiceTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('prev_time', models.CharField(blank=True, max_length=255, null=True)),
                ('prev_time_rad', models.CharField(blank=True, max_length=255, null=True)),
                ('after_time', models.CharField(blank=True, max_length=255, null=True)),
                ('after_time_rad', models.CharField(blank=True, max_length=255, null=True)),
                ('diff', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_service_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('main_type', models.CharField(blank=True, max_length=30, null=True)),
                ('sub_type', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('regist_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('view_date', models.DateTimeField(blank=True, null=True)),
                ('send_title', models.CharField(blank=True, max_length=100, null=True)),
                ('send_content', models.TextField(blank=True, null=True)),
                ('send_yn', models.CharField(blank=True, max_length=10, null=True)),
                ('send_date', models.DateTimeField(blank=True, null=True)),
                ('delete_yn', models.CharField(blank=True, max_length=10, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_support',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('phone_country', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=8, null=True)),
                ('sns_code', models.CharField(blank=True, max_length=100, null=True)),
                ('sns_name', models.CharField(blank=True, max_length=100, null=True)),
                ('rec', models.CharField(blank=True, max_length=100, null=True)),
                ('regist_rec', models.CharField(blank=True, max_length=100, null=True)),
                ('regist_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('regist_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('active_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('is_staff', models.IntegerField(blank=True, null=True)),
                ('delete_yn', models.CharField(blank=True, max_length=1, null=True)),
                ('black_yn', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'tbl_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('attempt', models.IntegerField(blank=True, null=True)),
                ('login_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('login_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_user_login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblWindowsVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver_code', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'tbl_windows_version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('use_time', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
    ]
